# Generated by Django 2.2 on 2020-02-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(default=None)),
                ('trail_map_url', models.URLField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allows_pets', models.BooleanField()),
                ('limited_access', models.BooleanField()),
                ('busy', models.CharField(max_length=255)),
                ('has_shade', models.BooleanField()),
                ('has_water', models.BooleanField()),
                ('has_bathrooms', models.BooleanField()),
                ('is_accessible', models.BooleanField()),
                ('is_kid_friendly', models.BooleanField()),
                ('permitted_activities', models.CharField(max_length=255)),
                ('natural_features', models.CharField(max_length=255)),
                ('has_playground', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('current_hiking_group', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_visited', models.BooleanField(default=False)),
                ('date_visited', models.DateTimeField(default=None)),
                ('public_notes', models.TextField(default=None)),
                ('private_notes', models.TextField(default=None)),
                ('hiking_group_at_visit_time', models.CharField(default=None, max_length=255)),
                ('rating', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='park_finder.Park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='park_finder.User')),
            ],
        ),
    ]
