# Generated by Django 2.2 on 2020-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visited',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
