# Generated by Django 2.2 on 2020-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_finder', '0002_auto_20200226_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_hiking_group',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hiking_group_at_visit_time',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='private_notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='public_notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
