# Generated by Django 2.2 on 2020-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_finder', '0003_auto_20200226_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.FloatField(default=33.59127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='longitue',
            field=models.FloatField(default=-117.814743),
            preserve_default=False,
        ),
    ]
