# Generated by Django 2.2 on 2020-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_finder', '0004_auto_20200228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitue',
            field=models.CharField(max_length=255),
        ),
    ]
